function FM_hyperparameter = xlearn2FM_main_k8(filename, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   ATL4FTW600 = IMPORTFILE1(FILENAME) Reads data from text file FILENAME
%   for the default selection.
%
%   ATL4FTW600 = IMPORTFILE1(FILENAME, STARTROW, ENDROW) Reads data from
%   rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   ATL4FTw600 = importfile1('AT_L4_FT_w600.txt', 1, 41);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2021/01/14 15:47:39

%% Initialize variables.
delimiter = ' ';
if nargin<=2
    startRow = 1;
    endRow = inf;
end

%% Format string for each line of text:
%   column2: double (%f)
%	column3: double (%f)
%   column4: double (%f)
%	column5: double (%f)
%   column6: double (%f)
%	column7: double (%f)
%   column8: double (%f)
%	column9: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%*s%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'MultipleDelimsAsOne', true, 'EmptyValue' ,NaN,'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Create output variable
hyperparameter = [dataArray{1:end-1}];
get_size_HP=size(hyperparameter);
xn=(get_size_HP(1)-1)/2;
kn=get_size_HP(2);
FM_hyperparameter.w0=hyperparameter(1,1);
FM_hyperparameter.wvmat = zeros(kn+1,xn);
FM_hyperparameter.wvmat(1,1:xn) = transpose(hyperparameter(2:xn+1,1));
FM_hyperparameter.wvmat(2:kn+1,1:xn) = transpose(hyperparameter(xn+2:2*xn+1,1:kn));



