function x0_candidates = x0_txtimport_SWA(filename, bitlength, startRow, endRow)
%IMPORTFILE1 Import numeric data from a text file as a matrix.
%   X0DUVARCN12T10TRAINT125QUBOQLM = IMPORTFILE1(FILENAME)
%   Reads data from text file FILENAME for the default selection.
%
%   X0DUVARCN12T10TRAINT125QUBOQLM = IMPORTFILE1(FILENAME, STARTROW, ENDROW)
%   Reads data from rows STARTROW through ENDROW of text file FILENAME.
%
% Example:
%   x0duvarcN12t10traint125quboqlm = importfile1('x0_duvarc_N12_t10_train_t1_25_qubo_qlm.txt', 1, 100);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2022/12/01 15:06:35

%% Initialize variables.
if nargin<=3
    startRow = 1;
    endRow = inf;
end

%% Format for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
% For more information, see the TEXTSCAN documentation.
formatspec='%1f';
for ifn=1:bitlength-2
    formatspec=[formatspec '%2f'];
end
formatSpec = [formatspec '%f%[^\n\r]'];
%formatSpec = '%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%2f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to the format.
% This call is based on the structure of the file used to generate this code. If an error occurs for a different file, try regenerating the code from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(1)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', '', 'WhiteSpace', '', 'TextType', 'string', 'HeaderLines', startRow(block)-1, 'ReturnOnError', false, 'EndOfLine', '\r\n');
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post processing code is included. To generate code which works for unimportable data, select unimportable cells in a file and regenerate the script.

%% Create output variable
x0_candidates = [dataArray{1:end-1}];
